services:
 
  app:    
    image: mcr.microsoft.com/devcontainers/base:noble
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity


  home-assistant:
    image: homeassistant/home-assistant  
    restart: unless-stopped    
    volumes:
      - home_assistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Madrid
    ports:
      - 8123:8123

volumes:
  home_assistant_config:    
